services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0
    hostname: oracle
    container_name: oracle
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      ORACLE_PASSWORD: testing
    volumes:
      - ./oracle/container-entrypoint-initdb.d:/container-entrypoint-initdb.d

  haproxy:
    image: haproxy:2.6
    hostname: haproxy
    container_name: haproxy
    depends_on:
      - keycloak1
      - keycloak2
    ports:
      - "8080:80"
      - "8404:8404"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  ldap:
    image: 389ds/dirsrv:2.4
    hostname: ldap
    container_name: ldap
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      DS_DM_PASSWORD: password
      DS_SUFFIX_NAME: dc=example,dc=com
    volumes:
      - ./ldap/init:/init
    entrypoint: /init/entrypoint.sh

  keycloak1:
    extends:
      file: common.yml
      service: keycloak
    hostname: keycloak1
    user: root
    container_name: keycloak1
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - ./keycloak/init:/init
    entrypoint: /init/entrypoint.sh
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  keycloak2:
    extends:
      file: common.yml
      service: keycloak
    hostname: keycloak2
    container_name: keycloak2
    depends_on:
      keycloak1:
        condition: service_healthy

